# Generated by Django 4.1 on 2022-11-12 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("movie_id", models.IntegerField(primary_key=True, serialize=False)),
                ("movie_name", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("movie_dir", models.CharField(max_length=100)),
                ("movie_act", models.CharField(max_length=200)),
                ("movie_ger", models.CharField(max_length=200)),
                ("movie_text", models.TextField(blank=True, null=True)),
                (
                    "movie_poster",
                    models.ImageField(upload_to="recommand/images/poster"),
                ),
                ("movie_link", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Ost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ost_name", models.CharField(max_length=200)),
                ("valence", models.FloatField()),
                ("acousticness", models.FloatField()),
                ("danceability", models.FloatField()),
                ("energy", models.FloatField()),
                ("loudness", models.FloatField()),
                ("tempo", models.FloatField()),
                ("rader_chart", models.ImageField(upload_to="recommand/images/rader")),
                (
                    "movie_id",
                    models.ForeignKey(
                        db_column="movie_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommand.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ost_nomal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_valence", models.FloatField()),
                ("num_acousticness", models.FloatField()),
                ("num_danceability", models.FloatField()),
                ("num_energy", models.FloatField()),
                ("num_loudness", models.FloatField()),
                ("num_tempo", models.FloatField()),
                ("num_gern", models.IntegerField()),
                ("num_mvdir", models.IntegerField()),
                ("cluster", models.IntegerField()),
                (
                    "ost_id",
                    models.ForeignKey(
                        db_column="ost_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommand.ost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie_rec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=200)),
                ("ch_ost_name", models.CharField(max_length=200)),
                ("ch_mov_name", models.CharField(max_length=200)),
                ("rec_ost_name", models.CharField(max_length=200)),
                ("rec_mov_name", models.CharField(max_length=200)),
                ("review", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ost_id",
                    models.ForeignKey(
                        db_column="ost_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommand.ost",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
