# Generated by Django 4.1 on 2022-11-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommand", "0002_alter_ost_acousticness_alter_ost_cluster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ost",
            name="acousticness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ost",
            name="danceability",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ost",
            name="energy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ost",
            name="loudness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ost",
            name="tempo",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ost",
            name="valence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
